import React,{useCallback,useEffect,useState} from 'react';
import SandField from './components/SandField';import RavenSand from './components/RavenSand';
const projects=[['Dispatch Intelligence','Operations','Real-time case intelligence, fleet knowledge and agent workflows.'],['Automation Bot','Automation','Telegram assignment, alerts, reporting and operational automation.'],['LearnInn','Platform','Multilingual learning platform, scheduling and client experience.'],['Custom CRM','Software','Purpose-built customer operations, workflows and communication.'],['Rekka Monitor','Infrastructure','Monitoring, alerts and API visibility for internal systems.'],['Web Experiences','Web','Fast, focused product sites and interactive digital experiences.']];
const services=[['01','Product engineering','From an operational problem to a production-ready web product.'],['02','Automation','Bots, integrations and workflows that remove repetitive work.'],['03','Internal systems','Dashboards, CRMs and tools designed around the way your team actually works.'],['04','Web experiences','Responsive, fast websites with purposeful interaction and motion.']];
const faq=[['What does REKKA build?','Custom software, internal tools, automation, bots and web experiences.'],['Can you improve an existing product?','Yes. We can audit an existing system, redesign the interface, fix workflows and extend the product without rebuilding everything blindly.'],['Do you handle deployment?','Yes. Projects can include deployment, environment setup and production handoff.'],['Can we start with a small scope?','Yes. A focused first release is often the best way to validate the workflow before expanding it.']];
const prices=[['Starter','Focused landing page or small product surface.','From €900',['Design direction','Responsive build','Core motion','Deployment']],['Product','A complete product/site experience for a growing business.','From €2,400',['UX + visual system','Multi-page build','Integrations','Advanced motion']],['Custom','Internal systems, automation, dashboards and complex workflows.','Let’s scope it',['Product discovery','Custom engineering','Automation / APIs','Production support']]];
function ThemeButton(){const[theme,setTheme]=useState(()=>localStorage.getItem('rekka-theme')||'dark');useEffect(()=>{document.documentElement.dataset.theme=theme;localStorage.setItem('rekka-theme',theme)},[theme]);return <button className="nav-control icon-btn" onClick={()=>setTheme(theme==='dark'?'light':'dark')} aria-label="Toggle theme">{theme==='dark'?'☼':'◐'}</button>}
function Nav(){const path=location.pathname.replace(/\/$/,'')||'/';const items=[['/','Home'],['/projects','Projects'],['/services','Services'],['/products','Products'],['/pricing','Pricing'],['/about','About'],['/faq','FAQ']];return <header className="topnav"><nav className="nav-left">{items.map(([u,n])=><a className={path===u?'active':''} href={u} key={u}>{n}</a>)}</nav><a href="/" className="wordmark">REKKA</a><div className="nav-right"><a className="nav-control search-link" href="/projects">⌕ <span>Search work...</span><kbd>⌘K</kbd></a><ThemeButton/><a className="nav-control start" href="/contact">Start a project</a></div></header>}
const Beam=({className=''})=><div className={'beam '+className}><i/><i/><i/></div>;
function Home(){return <main><section className="hero raven-hero"><SandField/><div className="hero-raven"><RavenSand/></div><div className="hero-inner reveal"><div className="version"><span>Independent software studio</span><b>2026</b></div><h1>Software for real<br/>work.</h1><p>We design and build custom software, automation, internal tools and web experiences that remove friction from everyday operations.</p><div className="hero-actions"><a href="/projects">Explore projects</a><a href="/contact" className="secondary">Start a project ↗</a></div></div></section><section className="section"><div className="section-head"><span>Capabilities</span><h2>The complete stack to turn an idea into a working product.</h2></div><div className="reference-card-grid">{services.slice(0,3).map((x,i)=><article className="reference-card" key={x[0]}><div className="reference-art"><SandField/><Beam className={`beam-${i}`}/><span>{['SYSTEM','LINK','FLOW'][i]}</span></div><div className="reference-copy"><h3>{x[1]}</h3><p>{x[2]}</p></div></article>)}</div></section><section className="terminal-section"><div className="terminal-copy"><small>FROM ZERO TO PRODUCTION</small><h2>Build in clear stages.</h2><div className="steps"><span>1 <b>Understand the workflow</b></span><span>2 <b>Shape the product</b></span><span>3 <b>Build + integrate</b></span><span>4 <b>Ship + improve</b></span></div></div><div className="terminal"><div className="terminal-tabs"><span>src/project/build.ts</span><span>□</span></div><pre><code>{`import { rekka } from "@rekka/build";

const product = await rekka.create({
  problem: "manual operations",
  layers: ["design", "software", "automation"],
  production: true
});

export default product;`}</code></pre></div></section><section className="section"><div className="section-head row"><div><span>Selected work</span><h2>Systems built around real workflows.</h2></div><a href="/projects">View all →</a></div><div className="project-preview">{projects.slice(0,3).map((p,i)=><a href="/projects" className="project-card silver-card" key={p[0]}><div className="project-art"><SandField/><Beam className={`beam-${i}`}/><strong>0{i+1}</strong></div><small>{p[1]}</small><h3>{p[0]}</h3><p>{p[2]}</p></a>)}</div></section><section className="proof-section"><div className="proof-head"><span>WHY REKKA</span><h2>Built for people doing the work.</h2></div><div className="proof-carousel"><button aria-label="Previous">‹</button><div className="proof-card"><p>“Less repetitive work. Clearer systems. Software shaped around the actual operation.”</p><strong>OPERATIONS</strong><span>Automation / internal tools</span></div><div className="proof-card"><p>“Interfaces should explain themselves and keep the important action obvious.”</p><strong>PRODUCT</strong><span>UX / web experiences</span></div><div className="proof-card"><p>“Start focused, ship something useful, then improve it with real feedback.”</p><strong>DELIVERY</strong><span>Build / deploy / iterate</span></div><button aria-label="Next">›</button></div></section><section className="closing"><Beam/><h2>Have something<br/>worth building?</h2><a href="/contact">Start a project →</a></section></main>}
function Projects(){const[q,setQ]=useState(''),[cat,setCat]=useState('All');const cats=['All',...new Set(projects.map(x=>x[1]))],data=projects.filter(p=>(cat==='All'||p[1]===cat)&&p.join(' ').toLowerCase().includes(q.toLowerCase()));return <main className="page"><div className="page-hero"><h1>Projects</h1><p>Software, automation and digital products built around practical problems.</p><label className="big-search">⌕<input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search projects"/></label></div><div className="filters"><span>Filter by category</span>{cats.map(c=><button className={cat===c?'active':''} onClick={()=>setCat(c)} key={c}>{c}</button>)}</div><div className="catalog">{data.map((p,i)=><article className="silver-card" key={p[0]}><div className="catalog-art"><SandField/><Beam className={`beam-${i%3}`}/></div><div><small>{p[1]}</small><h2>{p[0]}</h2><p>{p[2]}</p></div></article>)}</div></main>}
function Services(){return <main className="docs-page"><aside className="docs-nav"><div className="docs-group"><b>Services</b>{services.map((x,i)=><a className={i===0?'current':''} href={'#s'+x[0]} key={x[0]}><span>{x[1]}</span></a>)}</div><div className="docs-group"><b>Process</b><a href="#discover">Discover</a><a href="#build">Build</a><a href="#launch">Launch</a></div></aside><article className="docs-content"><h1>Services</h1><p className="lead">Focused product and engineering work—from the first operational problem through production.</p>{services.map((x,i)=><section id={'s'+x[0]} key={x[0]}><div className="service-kicker">{x[0]} / SERVICE</div><h2>{x[1]}</h2><p>{x[2]} We define the useful scope first, keep the interface understandable, and build around measurable operational value.</p>{i===0&&<div className="info-callout"><b>i</b><span>Every engagement starts with the workflow, not a pre-selected technology stack.</span></div>}</section>)}<section id="discover"><div className="service-kicker">PROCESS</div><h2>Discover → Build → Launch</h2><p>We identify the constraint, prototype the useful path, build the system, then refine it against real use.</p></section></article><aside className="toc"><b>On this page</b>{services.map(x=><a href={'#s'+x[0]} key={x[0]}>{x[1]}</a>)}<hr/><a href="/contact">Start a project ↗</a><a href="/pricing">View pricing</a></aside></main>}
function Products(){return <main className="page"><div className="page-hero"><h1>Products</h1><p>Reusable REKKA systems and product experiments.</p></div><div className="catalog products">{projects.slice(0,4).map((p,i)=><article className="silver-card" key={p[0]}><div className="catalog-art"><SandField/><Beam className={`beam-${i%3}`}/></div><div><small>{p[1]}</small><h2>{p[0]}</h2><p>{p[2]}</p></div></article>)}</div></main>}
function Pricing(){return <main className="page pricing-page"><div className="page-hero"><h1>Pricing</h1><p>Clear starting points. Final scope depends on what the product actually needs.</p></div><div className="pricing-grid">{prices.map((p,i)=><article className="price-card silver-card" key={p[0]}><small>0{i+1}</small><h2>{p[0]}</h2><p>{p[1]}</p><strong>{p[2]}</strong><ul>{p[3].map(x=><li key={x}>{x}</li>)}</ul><a href="/contact">Discuss this scope →</a></article>)}</div></main>}
function About(){return <main className="simple-page"><small>ABOUT REKKA</small><h1>Small studio.<br/>Focused work.</h1><p>REKKA builds practical software for teams that need something clearer, faster or more useful than the tools they have today.</p><div className="about-grid">{[['01','Understand','Start with the actual workflow and constraints.'],['02','Shape','Turn the problem into a clear product structure.'],['03','Build','Design, engineer, test and ship.']].map(x=><div className="silver-card" key={x[0]}><b>{x[0]}</b><h3>{x[1]}</h3><p>{x[2]}</p></div>)}</div></main>}
function FAQ(){const[open,setOpen]=useState(0);return <main className="page faq-page"><div className="page-hero"><h1>Frequently asked questions</h1><p>Everything you need to know before starting a project with REKKA.</p></div><div className="faq-list">{faq.map((x,i)=><button onClick={()=>setOpen(open===i?-1:i)} className={open===i?'open':''} key={x[0]}><span>{x[0]}<b>{open===i?'⌃':'⌄'}</b></span><div className="faq-answer" aria-hidden={open!==i}><p>{x[1]}</p></div></button>)}</div></main>}
function Contact(){const[sent,setSent]=useState(false);async function submit(e){e.preventDefault();const fd=new FormData(e.currentTarget);try{const r=await fetch('/api/feedback',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(fd))});if(r.ok)setSent(true);else setSent(true)}catch{setSent(true)}}return <main className="contact-page"><div className="contact-copy"><small>START A PROJECT</small><h1>Tell us what<br/>needs to exist.</h1><p>A short description is enough to start.</p><div className="contact-meta"><span>01 / Tell us the problem</span><span>02 / We shape the useful scope</span><span>03 / Build when it makes sense</span></div></div><form onSubmit={submit}>{sent?<div className="form-success"><small>MESSAGE RECEIVED</small><h2>We’ll take it from here.</h2><p>Your project note is ready for review.</p><a href="/">Back home →</a></div>:<><div className="form-head"><span>Project brief</span><span>01—03</span></div><label><span>Name</span><input name="name" required placeholder="Your name"/></label><label><span>Email</span><input name="email" type="email" required placeholder="you@company.com"/></label><label><span>Project details</span><textarea name="message" rows="8" required placeholder="What are you trying to build or fix?"/></label><button>Send message <span>→</span></button></>}</form></main>}
function Router(){let path=location.pathname.replace(/\/$/,'')||'/';return path==='/projects'?<Projects/>:path==='/services'?<Services/>:path==='/products'?<Products/>:path==='/pricing'?<Pricing/>:path==='/about'?<About/>:path==='/faq'?<FAQ/>:path==='/contact'?<Contact/>:<Home/>}
export default function App(){useEffect(()=>{requestAnimationFrame(()=>document.body.classList.add('ready'))},[]);return <><Nav/><Router/><footer><a href="/" className="wordmark">REKKA</a><span>Software / Automation / Web</span><span>© 2026</span></footer></>}
