import React,{useCallback,useEffect,useMemo,useState} from 'react';
import Loader from './components/Loader';

const projects=[
 ['Dispatch Intelligence','Operations','Real-time case intelligence, fleet knowledge and agent workflows.'],
 ['Automation Bot','Automation','Telegram assignment, alerts, reporting and operational automation.'],
 ['LearnInn','Platform','Multilingual learning platform, scheduling and client experience.'],
 ['Custom CRM','Software','Purpose-built customer operations, workflows and communication.'],
 ['Rekka Monitor','Infrastructure','Monitoring, alerts and API visibility for internal systems.'],
 ['Web Experiences','Web','Fast, focused product sites and interactive digital experiences.']
];
const services=[['01','Product engineering','From an operational problem to a production-ready web product.'],['02','Automation','Bots, integrations and workflows that remove repetitive work.'],['03','Internal systems','Dashboards, CRMs and tools designed around the way your team actually works.'],['04','Web experiences','Responsive, fast websites with purposeful interaction and motion.']];
const faq=[['What does REKKA build?','Custom software, internal tools, automation, bots and web experiences.'],['Can you improve an existing product?','Yes. We can audit an existing system, redesign the interface, fix workflows and extend the product without rebuilding everything blindly.'],['Do you handle deployment?','Yes. Projects can include deployment, environment setup and production handoff.'],['Can we start with a small scope?','Yes. A focused first release is often the best way to validate the workflow before expanding it.']];

function ThemeButton(){const[theme,setTheme]=useState(()=>localStorage.getItem('rekka-theme')||'dark');useEffect(()=>{document.documentElement.dataset.theme=theme;localStorage.setItem('rekka-theme',theme)},[theme]);return <button className="nav-control icon-btn" onClick={()=>setTheme(theme==='dark'?'light':'dark')} aria-label="Toggle theme">{theme==='dark'?'☼':'◐'}</button>}
function Nav(){return <header className="topnav"><nav className="nav-left"><a href="/">Home</a><a href="/projects">Projects</a><a href="/services">Services</a><a href="/products">Products</a><a href="/about">About</a><a href="/faq">FAQ</a></nav><a href="/" className="wordmark">REKKA</a><div className="nav-right"><a className="nav-control search-link" href="/projects">⌕ <span>Search work...</span><kbd>⌘K</kbd></a><ThemeButton/><a className="nav-control start" href="/contact">Start a project</a></div></header>}
const Beam=({className=''})=><div className={'beam '+className}><i/><i/><i/></div>;
function Home(){return <main><section className="hero"><Beam/><div className="hero-inner"><div className="version"><span>Independent software studio</span><b>2026</b></div><h1>Software for real<br/>work.</h1><p>We design and build custom software, automation, internal tools and web experiences that remove friction from everyday operations.</p><div className="hero-actions"><a href="/projects">Explore projects</a><a href="/contact" className="secondary">Start a project ↗</a></div></div></section><section className="section"><div className="section-head"><span>Capabilities</span><h2>The complete stack to turn an idea into a working product.</h2></div><div className="feature-grid">{services.map(x=><article key={x[0]}><small>{x[0]}</small><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></section><section className="terminal-section"><div className="terminal-copy"><small>FROM IDEA TO PRODUCTION</small><h2>Built clean.<br/>Made to work.</h2><p>Clear product thinking, focused interfaces and practical engineering—without an agency maze.</p></div><div className="terminal"><div className="terminal-tabs"><span>project.ts</span><span>● ● ●</span></div><pre><code>{`const project = await rekka.build({\n  problem: "manual operations",\n  approach: ["design", "software", "automation"],\n  outcome: "less friction"\n})\n\n✓ structure defined\n✓ interface shipped\n✓ production ready`}</code></pre></div></section><section className="section"><div className="section-head row"><div><span>Selected work</span><h2>Systems built around real workflows.</h2></div><a href="/projects">View all →</a></div><div className="project-preview">{projects.slice(0,3).map((p,i)=><a href="/projects" className="project-card" key={p[0]}><div className="project-art"><Beam className={`beam-${i}`}/><strong>0{i+1}</strong></div><small>{p[1]}</small><h3>{p[0]}</h3><p>{p[2]}</p></a>)}</div></section><section className="closing"><Beam/><h2>Have something<br/>worth building?</h2><a href="/contact">Start a project →</a></section></main>}
function Projects(){const[q,setQ]=useState('');const[cat,setCat]=useState('All');const cats=['All',...new Set(projects.map(x=>x[1]))];const data=projects.filter(p=>(cat==='All'||p[1]===cat)&&p.join(' ').toLowerCase().includes(q.toLowerCase()));return <main className="page"><div className="page-hero"><h1>Projects</h1><p>Software, automation and digital products built around practical problems.</p><label className="big-search">⌕<input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search projects"/></label></div><div className="filters"><span>Filter by category</span>{cats.map(c=><button className={cat===c?'active':''} onClick={()=>setCat(c)} key={c}>{c}</button>)}</div><div className="catalog">{data.map((p,i)=><article key={p[0]}><div className="catalog-art"><Beam className={`beam-${i%3}`}/></div><div><small>{p[1]}</small><h2>{p[0]}</h2><p>{p[2]}</p></div></article>)}</div></main>}
function Services(){return <main className="docs-page"><aside><b>Services</b>{services.map(x=><a href={'#s'+x[0]} key={x[0]}>{x[1]}</a>)}<b>Process</b><a href="#discover">Discover</a><a href="#build">Build</a><a href="#launch">Launch</a></aside><article className="docs-content"><h1>Services</h1><p className="lead">Focused software work from initial problem through production.</p>{services.map(x=><section id={'s'+x[0]} key={x[0]}><h2>{x[1]}</h2><p>{x[2]} We define the useful scope first, keep the interface understandable, and build around measurable operational value.</p></section>)}</article><aside className="toc"><b>On this page</b>{services.map(x=><a href={'#s'+x[0]} key={x[0]}>{x[1]}</a>)}</aside></main>}
function Products(){return <main className="page"><div className="page-hero"><h1>Products</h1><p>Reusable REKKA systems and product experiments.</p></div><div className="catalog products">{projects.slice(0,4).map((p,i)=><article key={p[0]}><div className="catalog-art"><Beam className={`beam-${i%3}`}/></div><div><small>{p[1]}</small><h2>{p[0]}</h2><p>{p[2]}</p></div></article>)}</div></main>}
function About(){return <main className="simple-page"><small>ABOUT REKKA</small><h1>Small studio.<br/>Focused work.</h1><p>REKKA builds practical software for teams that need something clearer, faster or more useful than the tools they have today.</p><div className="about-grid"><div><b>01</b><h3>Understand</h3><p>Start with the actual workflow and constraints.</p></div><div><b>02</b><h3>Shape</h3><p>Turn the problem into a clear product structure.</p></div><div><b>03</b><h3>Build</h3><p>Design, engineer, test and ship.</p></div></div></main>}
function FAQ(){const[open,setOpen]=useState(0);return <main className="page faq-page"><div className="page-hero"><h1>Frequently asked questions</h1><p>Everything you need to know before starting a project with REKKA.</p></div><div className="faq-list">{faq.map((x,i)=><button onClick={()=>setOpen(open===i?-1:i)} className={open===i?'open':''} key={x[0]}><span>{x[0]}<b>{open===i?'⌃':'⌄'}</b></span>{open===i&&<p>{x[1]}</p>}</button>)}</div></main>}
function Contact(){return <main className="contact-page"><div><small>START A PROJECT</small><h1>Tell us what<br/>needs to exist.</h1><p>A short description is enough to start.</p></div><form onSubmit={e=>e.preventDefault()}><label>Name<input required/></label><label>Email<input type="email" required/></label><label>Project details<textarea rows="7" required/></label><button>Send message →</button></form></main>}
function Router(){let path=location.pathname.replace(/\/$/,'')||'/';return path==='/projects'?<Projects/>:path==='/services'?<Services/>:path==='/products'?<Products/>:path==='/about'?<About/>:path==='/faq'?<FAQ/>:path==='/contact'?<Contact/>:<Home/>}
export default function App(){const[intro,setIntro]=useState(()=>sessionStorage.getItem('rekka-intro')!=='seen');const done=useCallback(()=>{sessionStorage.setItem('rekka-intro','seen');setIntro(false)},[]);return <>{intro&&<Loader onDone={done}/>}<Nav/><Router/><footer><a href="/" className="wordmark">REKKA</a><span>Software / Automation / Web</span><span>© 2026</span></footer></>}
